server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Serve static files
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy for Auth API
    location /api/auth/ {
        proxy_pass http://auth-api:8081/api/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Reverse proxy for Python ML API
    location /api/ml/ {
        proxy_pass http://ml-api:8000/api/ml/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
